### ISSUE TITLE
Blank Home screen issue for some players

### ISSUE THREAD

**Issue by BPJ-Project** [blastersuraj/ef-phone#1]
Phone working fine on my end, but when other players in serv open phone and press the fingerprint the phone then goes completely blank and see through
![ef-phone](https://user-images.githubusercontent.com/79064551/232939236-6c53118d-982b-4ead-94c1-2f7ba4b14b88.png)

**Comment by BPJ-Project** [comment]
Update error is....

[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ef-phone/server/main.lua:199: attempt to index a nil value (global 'Garages')
[      script:qb-core] > ref (@ef-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by BPJ-Project** [comment]
Fixed Issue... code just had Garages insterad of Config.Garages

local garageresult = MySQL.Sync.fetchAll('SELECT * FROM player_vehicles WHERE citizenid = ?', {Player.PlayerData.citizenid})
        if garageresult[1] ~= nil then
            for k, v in pairs(garageresult) do
                local vehicleModel = v.vehicle
                if (QBCore.Shared.Vehicles[vehicleModel] ~= nil) and (Config.Garages[v.garage] ~= nil) then
                    v.garage = Config.Garages[v.garage].label
                    v.vehicle = QBCore.Shared.Vehicles[vehicleModel].name
                    v.brand = QBCore.Shared.Vehicles[vehicleModel].brand
                end

            end
            PhoneData.Garage = garageresult
        end

**Comment by blastersuraj** [comment]
those u have facing blank screen issue go and download again the latest version from tebex we update and fixed this error

**Comment by Ackkz** [comment]
Not Working for me aswell

**Comment by blastersuraj** [comment]
> Phone working fine on my end, but when other players in serv open phone and press the fingerprint the phone then goes completely blank and see through ![ef-phone](https://user-images.githubusercontent.com/79064551/232939236-6c53118d-982b-4ead-94c1-2f7ba4b14b88.png)

make sure old sql was deleted and new sql install properly

**Comment by blastersuraj** [comment]
..

**Comment by blastersuraj** [comment]
..
