### ISSUE TITLE
[Request] RenewedScripts-QB-Phone

### ISSUE THREAD

**Issue by SirOMGitsYOU** [blastersuraj/ef-phone#4]
A Fork/Branch version of this but with implementation for the renewed scripts qb-phone eco system and apps would be a fantastic addition to this script! 

https://github.com/Renewed-Scripts/qb-phone

**Comment by blastersuraj** [comment]
..

**Comment by blastersuraj** [comment]
> A Fork/Branch version of this but with implementation for the renewed scripts qb-phone eco system and apps would be a fantastic addition to this script!
> 
> https://github.com/Renewed-Scripts/qb-phone

thx
